name: Deploy backend

on:
  push: [ main ]
  paths: 
    - 'backend/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    setps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: Dockerfile
          acrName: circuitoapp
          imageToBuid: circuitoapp.azurecr.io/circuitoapp-api:latest
          containerAppName: circuitoapp-api
          resourceGroup: rg-circuitoapp
          containerAppEnvironment: env-circuitoapp
          targetPort: 8181
          ingress: external
          environmentVariables: |
            MONGODB_REMOTE_URI=${{ secrets.MONGODB_REMOTE_URI }}
            MONGODB_REMOOTE_DB_NAME=${{ secrets.MONGODB_REMOOTE_DB_NAME }}
            MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}
            API_PORT=8181
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}

